/**
 * CEBIZPAY API ENDPOINTS REGISTRY
 * Maps 100% of client routes from docs/endpoints.json.
 */

const API_VERSION = 'v1';
const BASE_PREFIX = `/api/${API_VERSION}`;

export const ENDPOINTS = {
    AUTH: {
      LOGIN: `${BASE_PREFIX}/auth/login`,
      ME: `${BASE_PREFIX}/auth/me`,
      MFA_VERIFY: `${BASE_PREFIX}/auth/mfa/verify`,
      MFA_TOGGLE: `${BASE_PREFIX}/auth/mfa/toggle`,
      REGISTER_PHONE: `${BASE_PREFIX}/auth/register/phone`,
      REGISTER_OTP_VERIFY: `${BASE_PREFIX}/auth/register/otp/verify`,
      CHANGE_PASSWORD: `${BASE_PREFIX}/auth/change-password`,
      ADMIN_REDEEM_INVITE: `${BASE_PREFIX}/auth/admin/redeem-invite`,
      REFRESH_TOKEN: `${BASE_PREFIX}/auth/refresh-token`,
      REVOKE_TOKEN: `${BASE_PREFIX}/auth/revoke-token`,
    },
    USER: {
      REFERRALS: {
        DASHBOARD: `${BASE_PREFIX}/profile/referrals`,
        GET_CODE: `${BASE_PREFIX}/profile/referrals/code`,
        CLAIM_CODE: `${BASE_PREFIX}/profile/referrals/claim`,
      },
      NOTIFICATIONS: {
        LIST: `${BASE_PREFIX}/notifications`,
        UNREAD_COUNT: `${BASE_PREFIX}/notifications/unread-count`,
        MARK_READ: (id) => `${BASE_PREFIX}/notifications/${id}/read`,
        MARK_ALL_READ: `${BASE_PREFIX}/notifications/read-all`,
        PREFERENCES: `${BASE_PREFIX}/notifications/preferences`,
        REGISTER_DEVICE: `${BASE_PREFIX}/notifications/device-token`,
      },
      ANNOUNCEMENTS: {
        PLATFORM: `${BASE_PREFIX}/announcements/platform`,
        WORKPLACE: `${BASE_PREFIX}/announcements/workplace`,
        ACTIVE: `${BASE_PREFIX}/announcements/active`,
        LIST: `${BASE_PREFIX}/announcements`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/announcements/${id}`,
        CREATE: `${BASE_PREFIX}/announcements`,
        UPDATE: (id) => `${BASE_PREFIX}/announcements/${id}`,
        DELETE: (id) => `${BASE_PREFIX}/announcements/${id}`,
      },
    },
    COMPLIANCE: {
      INDIVIDUAL_KYC: {
        SUBMIT_DOCUMENTS: (id) => `${BASE_PREFIX}/individuals/${id}/kyc-documents`,
        GET_DOCUMENTS: (id) => `${BASE_PREFIX}/individuals/${id}/kyc-documents`,
        UPDATE_STATUS: (id) => `${BASE_PREFIX}/individuals/${id}/kyc-status`,
      },
      ORGANIZATION_KYB: {
        REGISTER_STEP1: `${BASE_PREFIX}/org/kyb/register-step1`,
        REGISTER_STEP2: `${BASE_PREFIX}/org/kyb/register-step2`,
        UPDATE_STATUS: (id) => `${BASE_PREFIX}/organizations/${id}/status`,
      },
      IDENTITY: {
        VERIFY_BVN: `${BASE_PREFIX}/compliance/verify/bvn`,
        VERIFY_NIN: `${BASE_PREFIX}/compliance/verify/nin`,
        VERIFY_BUSINESS: `${BASE_PREFIX}/compliance/verify/business`,
        VERIFY_DOCUMENT: `${BASE_PREFIX}/compliance/verify/document`,
        VERIFY_BIOMETRICS: `${BASE_PREFIX}/compliance/verify/biometrics`,
        SCREEN_AML: `${BASE_PREFIX}/compliance/screen/aml`,
        CHECK_ELIGIBILITY: `${BASE_PREFIX}/compliance/eligibility/check`,
        CDD_PROFILE: `${BASE_PREFIX}/compliance/cdd/profile`,
        SUBMIT_EDD_INFO: (id) => `${BASE_PREFIX}/compliance/edd/cases/${id}/information`,
        BENEFICIAL_OWNERS: `${BASE_PREFIX}/compliance/beneficial-owners`,
      },
    },
    WALLET: {
      GET_DETAILS: `${BASE_PREFIX}/wallet`,
      GET_TRANSACTIONS: `${BASE_PREFIX}/wallet/transactions`,
      PEER_TRANSFER: `${BASE_PREFIX}/wallet/transfer/peer`,
      BANK_TRANSFER: `${BASE_PREFIX}/wallet/transfer/bank`,
      RESOLVE_ACCOUNT: `${BASE_PREFIX}/wallet/transfer/resolve-account`,
      EXTERNAL_ACCOUNTS: `${BASE_PREFIX}/wallet/external-accounts`,
      EXTERNAL_ACCOUNT_BY_ID: (id) => `${BASE_PREFIX}/wallet/external-accounts/${id}`,
      PROVISION_MONNIFY: `${BASE_PREFIX}/wallet/external-accounts/monnify`,
      SET_PRIMARY_EXTERNAL: (id) => `${BASE_PREFIX}/wallet/external-accounts/${id}/primary`,
      FUNDING_STATUS: (id) => `${BASE_PREFIX}/wallet/funding/${id}`,
      VIRTUAL_ACCOUNTS: {
        PROVISION: `${BASE_PREFIX}/virtual-accounts/provision`,
        PRIMARY: `${BASE_PREFIX}/virtual-accounts/primary`,
      },
    },
    CARDS: {
      SAVED_CARDS: `${BASE_PREFIX}/saved-cards`,
      GET_BY_ID: (id) => `${BASE_PREFIX}/saved-cards/${id}`,
      DELETE: (id) => `${BASE_PREFIX}/saved-cards/${id}`,
      SET_DEFAULT: (id) => `${BASE_PREFIX}/saved-cards/${id}/default`,
      CHARGE: `${BASE_PREFIX}/saved-cards/charge`,
      FUNDING: {
        INITIALIZE: `${BASE_PREFIX}/card-funding/initialize`,
        VERIFY: `${BASE_PREFIX}/card-funding/verify`,
        STATUS: (reference) => `${BASE_PREFIX}/card-funding/status/${reference}`,
      },
      VERIFICATION: {
        INITIALIZE: `${BASE_PREFIX}/card-verification/initialize`,
        COMPLETE: `${BASE_PREFIX}/card-verification/complete`,
      },
      REFUNDS: {
        REQUEST: `${BASE_PREFIX}/card-refunds/request`,
        LIST: `${BASE_PREFIX}/card-refunds`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/card-refunds/${id}`,
      },
    },
    WORK: {
      JOIN_ORGANIZATION: `${BASE_PREFIX}/work/organisation/join`,
      SAVINGS: {
        PREVIEW: `${BASE_PREFIX}/work/savings/preview`,
        OPEN: `${BASE_PREFIX}/work/savings`,
        LIST: `${BASE_PREFIX}/work/savings`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/work/savings/${id}`,
        CONTRIBUTE: (id) => `${BASE_PREFIX}/work/savings/${id}/contribute`,
        WITHDRAW_PREVIEW: (id) => `${BASE_PREFIX}/work/savings/${id}/withdraw/preview`,
        WITHDRAW: (id) => `${BASE_PREFIX}/work/savings/${id}/withdraw`,
      },
      LOANS: {
        PREVIEW: `${BASE_PREFIX}/work/loans/preview`,
        APPLICATIONS: `${BASE_PREFIX}/work/loans/applications`,
        APPLICATION_BY_ID: (id) => `${BASE_PREFIX}/work/loans/applications/${id}`,
        CONTRACTS: `${BASE_PREFIX}/work/loans/contracts`,
        CONTRACT_BY_ID: (id) => `${BASE_PREFIX}/work/loans/contracts/${id}`,
      },
      THRIFT: {
        CREATE: `${BASE_PREFIX}/work/thrift`,
        LIST: `${BASE_PREFIX}/work/thrift`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/work/thrift/${id}`,
        INVITE: (id) => `${BASE_PREFIX}/work/thrift/${id}/invite`,
        JOIN: `${BASE_PREFIX}/work/thrift/join`,
        SELECT_POSITION: (id) => `${BASE_PREFIX}/work/thrift/${id}/position`,
        MEMBERS: (id) => `${BASE_PREFIX}/work/thrift/${id}/members`,
        CYCLES: (id) => `${BASE_PREFIX}/work/thrift/${id}/cycles`,
        LOCK: (id) => `${BASE_PREFIX}/work/thrift/${id}/lock`,
        LEAVE: (id, memberId) => `${BASE_PREFIX}/work/thrift/${id}/members/${memberId}/leave`,
      },
    },
    ORGANIZATION: {
      DEPARTMENTS: {
        LIST: `${BASE_PREFIX}/org/departments`,
        CREATE: `${BASE_PREFIX}/org/departments`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/departments/${id}`,
        UPDATE: (id) => `${BASE_PREFIX}/org/departments/${id}`,
        DELETE: (id) => `${BASE_PREFIX}/org/departments/${id}`,
      },
      ROLES: {
        LIST: `${BASE_PREFIX}/org/roles`,
        CREATE: `${BASE_PREFIX}/org/roles`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/roles/${id}`,
        UPDATE: (id) => `${BASE_PREFIX}/org/roles/${id}`,
        DELETE: (id) => `${BASE_PREFIX}/org/roles/${id}`,
      },
      LEVELS: {
        LIST: `${BASE_PREFIX}/org/levels`,
        CREATE: `${BASE_PREFIX}/org/levels`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/levels/${id}`,
        UPDATE: (id) => `${BASE_PREFIX}/org/levels/${id}`,
        DELETE: (id) => `${BASE_PREFIX}/org/levels/${id}`,
      },
      STAFF: {
        LIST: `${BASE_PREFIX}/org/staff`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/staff/${id}`,
        CREATE: `${BASE_PREFIX}/org/staff/create`,
        INVITE: `${BASE_PREFIX}/org/staff/invite`,
        INVITE_BULK: `${BASE_PREFIX}/org/staff/invite-bulk`,
        ACCEPT_INVITE: `${BASE_PREFIX}/org/staff/accept`,
        ASSIGN: (id) => `${BASE_PREFIX}/org/staff/${id}/assign`,
        SUSPEND: (id) => `${BASE_PREFIX}/org/staff/${id}/suspend`,
        REACTIVATE: (id) => `${BASE_PREFIX}/org/staff/${id}/reactivate`,
        TERMINATE: (id) => `${BASE_PREFIX}/org/staff/${id}/terminate`,
      },
      PAYROLL: {
        PREVIEW: `${BASE_PREFIX}/org/payroll/preview`,
        CALCULATE: `${BASE_PREFIX}/org/payroll/calculate`,
        EXECUTE: `${BASE_PREFIX}/org/payroll/execute`,
        BATCHES: `${BASE_PREFIX}/org/payroll/batches`,
        BATCH_BY_ID: (id) => `${BASE_PREFIX}/org/payroll/batches/${id}`,
        RETRY_FAILED: (batchId) => `${BASE_PREFIX}/org/payroll/${batchId}/retry-failed`,
        CANCEL_BATCH: (batchId) => `${BASE_PREFIX}/org/payroll/${batchId}/cancel`,
        VOUCHERS: (id) => `${BASE_PREFIX}/org/payroll/vouchers/${id}`,
        UPDATE_VOUCHER: (id) => `${BASE_PREFIX}/org/payroll/vouchers/${id}`,
      },
    },
    ERP: {
      INVENTORY: {
        ITEMS: `${BASE_PREFIX}/org/inventory/items`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/inventory/items/${id}`,
        CREATE: `${BASE_PREFIX}/org/inventory/items`,
        UPDATE: (id) => `${BASE_PREFIX}/org/inventory/items/${id}`,
        STOCK_IN: (id) => `${BASE_PREFIX}/org/inventory/items/${id}/stock-in`,
        STOCK_OUT: (id) => `${BASE_PREFIX}/org/inventory/items/${id}/stock-out`,
        ADJUST: (id) => `${BASE_PREFIX}/org/inventory/items/${id}/adjust`,
        MOVEMENTS: `${BASE_PREFIX}/org/inventory/movements`,
        VALUATION_POLICY: `${BASE_PREFIX}/org/inventory/valuation-policy`,
      },
      ORDERS: {
        PURCHASE: {
          LIST: `${BASE_PREFIX}/org/orders/purchase`,
          CREATE: `${BASE_PREFIX}/org/orders/purchase`,
          GET_BY_ID: (id) => `${BASE_PREFIX}/org/orders/purchase/${id}`,
          RECEIVE_ITEM: (orderId, itemId) => `${BASE_PREFIX}/org/orders/purchase/${orderId}/items/${itemId}/receive`,
          CANCEL: (id) => `${BASE_PREFIX}/org/orders/purchase/${id}/cancel`,
        },
        SALES: {
          LIST: `${BASE_PREFIX}/org/orders/sales`,
          CREATE: `${BASE_PREFIX}/org/orders/sales`,
          GET_BY_ID: (id) => `${BASE_PREFIX}/org/orders/sales/${id}`,
          CONFIRM: (id) => `${BASE_PREFIX}/org/orders/sales/${id}/confirm`,
          FULFILL_ITEM: (orderId, itemId) => `${BASE_PREFIX}/org/orders/sales/${orderId}/items/${itemId}/fulfill`,
          CANCEL: (id) => `${BASE_PREFIX}/org/orders/sales/${id}/cancel`,
        },
      },
      INVOICES: {
        LIST: `${BASE_PREFIX}/org/invoices`,
        CREATE: `${BASE_PREFIX}/org/invoices`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/invoices/${id}`,
        RECORD_PAYMENT: (id) => `${BASE_PREFIX}/org/invoices/${id}/payments`,
      },
      RECEIPTS: {
        LIST: `${BASE_PREFIX}/org/receipts`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/receipts/${id}`,
        BY_INVOICE: (invoiceId) => `${BASE_PREFIX}/org/receipts/by-invoice/${invoiceId}`,
      },
      EXPENSES: {
        OPERATING: {
          LIST: `${BASE_PREFIX}/org/expenses/operating`,
          CREATE: `${BASE_PREFIX}/org/expenses/operating`,
          GET_BY_ID: (id) => `${BASE_PREFIX}/org/expenses/operating/${id}`,
          PAY: (id) => `${BASE_PREFIX}/org/expenses/operating/${id}/pay`,
        },
        VOUCHERS: {
          LIST: `${BASE_PREFIX}/org/company-vouchers`,
          CREATE: `${BASE_PREFIX}/org/company-vouchers`,
          GET_BY_ID: (id) => `${BASE_PREFIX}/org/company-vouchers/${id}`,
          PAY: (id) => `${BASE_PREFIX}/org/company-vouchers/${id}/pay`,
          UPDATE_METADATA: (id) => `${BASE_PREFIX}/org/company-vouchers/${id}/metadata`,
        },
      },
      SUPPLIERS: {
        LIST: `${BASE_PREFIX}/org/suppliers`,
        CREATE: `${BASE_PREFIX}/org/suppliers`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/suppliers/${id}`,
        UPDATE: (id) => `${BASE_PREFIX}/org/suppliers/${id}`,
        DELETE: (id) => `${BASE_PREFIX}/org/suppliers/${id}`,
      },
      CUSTOMERS: {
        LIST: `${BASE_PREFIX}/org/customers`,
        CREATE: `${BASE_PREFIX}/org/customers`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/customers/${id}`,
        UPDATE: (id) => `${BASE_PREFIX}/org/customers/${id}`,
        DELETE: (id) => `${BASE_PREFIX}/org/customers/${id}`,
      },
      SERVICES: {
        LIST: `${BASE_PREFIX}/org/services`,
        CREATE: `${BASE_PREFIX}/org/services`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/org/services/${id}`,
        UPDATE: (id) => `${BASE_PREFIX}/org/services/${id}`,
        DELETE: (id) => `${BASE_PREFIX}/org/services/${id}`,
      },
      REPORTS: {
        PROFIT_LOSS: `${BASE_PREFIX}/org/reports/profit-loss`,
        SALES: `${BASE_PREFIX}/org/reports/sales`,
        PURCHASES: `${BASE_PREFIX}/org/reports/purchases`,
        SETTLEMENTS: `${BASE_PREFIX}/org/reports/settlements`,
      },
      SAVINGS: {
        PLANS: `${BASE_PREFIX}/org/savings/plans`,
        PLAN_BY_ID: (id) => `${BASE_PREFIX}/org/savings/plans/${id}`,
        PARTICIPANTS: (id) => `${BASE_PREFIX}/org/savings/plans/${id}/participants`,
        ACCOUNTS: `${BASE_PREFIX}/org/savings/accounts`,
      },
      THRIFT: {
        GROUPS: `${BASE_PREFIX}/org/thrift/groups`,
        LOCK: (id) => `${BASE_PREFIX}/org/thrift/${id}/lock`,
      },
      LOANS: {
        CORPORATE_PLANS: `${BASE_PREFIX}/corporate-loan-plans`,
        CORPORATE_PLAN_BY_ID: (id) => `${BASE_PREFIX}/corporate-loan-plans/${id}`,
        APPLICATIONS: `${BASE_PREFIX}/org/loans/applications`,
        APPLICATION_BY_ID: (id) => `${BASE_PREFIX}/org/loans/applications/${id}`,
        APPROVE_APPLICATION: (id) => `${BASE_PREFIX}/org/loans/applications/${id}/approve`,
        DECLINE_APPLICATION: (id) => `${BASE_PREFIX}/org/loans/applications/${id}/decline`,
      },
    },
    RECRUITMENT: {
      ORG: {
        JOBS: `${BASE_PREFIX}/org/recruitment/jobs`,
        JOB_BY_ID: (id) => `${BASE_PREFIX}/org/recruitment/jobs/${id}`,
        PUBLISH_JOB: (id) => `${BASE_PREFIX}/org/recruitment/jobs/${id}/publish`,
        CLOSE_JOB: (id) => `${BASE_PREFIX}/org/recruitment/jobs/${id}/close`,
        CANCEL_JOB: (id) => `${BASE_PREFIX}/org/recruitment/jobs/${id}/cancel`,
        APPLICATIONS: (jobId) => `${BASE_PREFIX}/org/recruitment/jobs/${jobId}/applications`,
        APPLICATION_BY_ID: (id) => `${BASE_PREFIX}/org/recruitment/applications/${id}`,
        REVIEW_APPLICATION: (id) => `${BASE_PREFIX}/org/recruitment/applications/${id}/review`,
        SHORTLIST_APPLICATION: (id) => `${BASE_PREFIX}/org/recruitment/applications/${id}/shortlist`,
        ACCEPT_APPLICATION: (id) => `${BASE_PREFIX}/org/recruitment/applications/${id}/accept`,
        REJECT_APPLICATION: (id) => `${BASE_PREFIX}/org/recruitment/applications/${id}/reject`,
      },
      PUBLIC: {
        JOBS: `${BASE_PREFIX}/recruitment/jobs`,
        JOB_BY_ID: (id) => `${BASE_PREFIX}/recruitment/jobs/${id}`,
        APPLY: (jobId) => `${BASE_PREFIX}/recruitment/jobs/${jobId}/applications`,
        WITHDRAW: (id) => `${BASE_PREFIX}/recruitment/applications/${id}/withdraw`,
      },
    },
    VAS: {
      OPERATORS_DETECT: `${BASE_PREFIX}/vas/operators/detect`,
      DATA_BUNDLES: `${BASE_PREFIX}/vas/data/bundles`,
      PURCHASE_AIRTIME: `${BASE_PREFIX}/vas/airtime`,
      PURCHASE_DATA: `${BASE_PREFIX}/vas/data`,
      TRANSACTION_BY_ID: (id) => `${BASE_PREFIX}/vas/transactions/${id}`,
    },
    SUPPORT: {
      TICKETS: `${BASE_PREFIX}/support/tickets`,
      TICKET_BY_ID: (id) => `${BASE_PREFIX}/support/tickets/${id}`,
      ADD_MESSAGE: (id) => `${BASE_PREFIX}/support/tickets/${id}/messages`,
      UPDATE_STATUS: (id) => `${BASE_PREFIX}/support/tickets/${id}/status`,
      KOLA: {
        START_SESSION: `${BASE_PREFIX}/support/kola/session`,
        INTERACT: `${BASE_PREFIX}/support/kola/interact`,
      },
    },
    ADMIN: {
      ORGANIZATIONS: {
        LIST: `${BASE_PREFIX}/admin/organizations`,
        GET_BY_ID: (id) => `${BASE_PREFIX}/admin/organizations/${id}`,
        UPDATE_STATUS: (id) => `${BASE_PREFIX}/organizations/${id}/status`,
        REVIEW_KYB: `${BASE_PREFIX}/admin/kyb/review`,
        PAYROLL_ANALYTICS: (id) => `${BASE_PREFIX}/admin/organizations/${id}/payroll-analytics`,
        STAFF: (id) => `${BASE_PREFIX}/admin/organizations/${id}/staff`,
        DOCUMENTS: (id) => `${BASE_PREFIX}/admin/organizations/${id}/documents`,
        EXPORT: `${BASE_PREFIX}/admin/organizations/export`,
      },
      DASHBOARD: {
        METRICS: `${BASE_PREFIX}/admin/dashboard/metrics`,
      },
      TREASURY: {
        SUMMARY: `${BASE_PREFIX}/admin/treasury/summary`,
      },
      ANALYTICS: {
        REVENUE: `${BASE_PREFIX}/admin/analytics/revenue`,
      },
      AUDIT_LOGS: `${BASE_PREFIX}/admin/audit-logs`,
      COMPLIANCE: {
        ASSESSMENT: (subjectType, subjectId) => `${BASE_PREFIX}/admin/compliance/assessments/${subjectType}/${subjectId}`,
        ASSESSMENT_HISTORY: (subjectType, subjectId) => `${BASE_PREFIX}/admin/compliance/assessments/${subjectType}/${subjectId}/history`,
        EVALUATE_RISK: `${BASE_PREFIX}/admin/compliance/assessments/evaluate`,
        EDD_CASES: `${BASE_PREFIX}/admin/compliance/edd/cases`,
        EDD_CASE_BY_ID: (id) => `${BASE_PREFIX}/admin/compliance/edd/cases/${id}`,
        REQUEST_EDD_INFO: (id) => `${BASE_PREFIX}/admin/compliance/edd/cases/${id}/request-information`,
        ASSIGN_EDD_REVIEWER: (id) => `${BASE_PREFIX}/admin/compliance/edd/cases/${id}/assign`,
        APPROVE_EDD: (id) => `${BASE_PREFIX}/admin/compliance/edd/cases/${id}/approve`,
        REJECT_EDD: (id) => `${BASE_PREFIX}/admin/compliance/edd/cases/${id}/reject`,
        PLACE_RESTRICTION: `${BASE_PREFIX}/admin/compliance/restrictions`,
        RELEASE_RESTRICTION: (id) => `${BASE_PREFIX}/admin/compliance/restrictions/${id}/release`,
        APPLY_OVERRIDE: `${BASE_PREFIX}/admin/compliance/overrides`,
      },
      MANAGE: {
        ADMINS: `${BASE_PREFIX}/admin/manage`,
        INVITE: `${BASE_PREFIX}/admin/manage/invite`,
        TOGGLE_STATUS: `${BASE_PREFIX}/admin/manage/toggle-status`,
        DELETE: (id) => `${BASE_PREFIX}/admin/manage/${id}`,
        GRANT_PERMISSION: (id) => `${BASE_PREFIX}/admin/manage/admins/${id}/permissions/grant`,
        REVOKE_PERMISSION: (id) => `${BASE_PREFIX}/admin/manage/admins/${id}/permissions/revoke`,
      },
      FEES: {
        POLICIES: `${BASE_PREFIX}/admin/fees/policies`,
        POLICY_BY_ID: (id) => `${BASE_PREFIX}/admin/fees/policies/${id}`,
        PLATFORM_POLICIES: `${BASE_PREFIX}/admin/fees/platform-policies`,
        PLATFORM_POLICY_BY_ID: (id) => `${BASE_PREFIX}/admin/fees/platform-policies/${id}`,
        BANK_TRANSFER_POLICIES: `${BASE_PREFIX}/admin/fees/bank-transfer-policies`,
        BANK_TRANSFER_POLICY_BY_ID: (id) => `${BASE_PREFIX}/admin/fees/bank-transfer-policies/${id}`,
      },
      RECONCILIATION: {
        RECORDS: `${BASE_PREFIX}/admin/reconciliation/records`,
        RECORD_BY_ID: (id) => `${BASE_PREFIX}/admin/reconciliation/records/${id}`,
        REQUERY: (id) => `${BASE_PREFIX}/admin/reconciliation/records/${id}/requery`,
        UNIFIED: `${BASE_PREFIX}/admin/reconciliation/unified`,
        UNIFIED_BY_ID: (id) => `${BASE_PREFIX}/admin/reconciliation/unified/${id}`,
      },
      REFERRALS: {
        SETTINGS: `${BASE_PREFIX}/admin/referrals/settings`,
        UPDATE_SETTINGS: `${BASE_PREFIX}/admin/referrals/settings`,
      },
      REVIEWS: {
        PENDING: `${BASE_PREFIX}/admin/reviews/pending`,
        DECISION: `${BASE_PREFIX}/admin/reviews/decision`,
        RECOVERIES: `${BASE_PREFIX}/admin/reviews/recoveries`,
        SETTLE_RECOVERY: (id) => `${BASE_PREFIX}/admin/reviews/recoveries/${id}/settle`,
      },
      SAVINGS_POLICIES: {
        POLICIES: `${BASE_PREFIX}/admin/savings-interest-policies`,
        CREATE: `${BASE_PREFIX}/admin/savings-interest-policies`,
      },
      THRIFT: {
        GROUPS: `${BASE_PREFIX}/admin/thrift/groups`,
        GROUP_BY_ID: (id) => `${BASE_PREFIX}/admin/thrift/groups/${id}`,
        DELINQUENCIES: `${BASE_PREFIX}/admin/thrift/delinquencies`,
        DISPUTES: `${BASE_PREFIX}/admin/thrift/disputes`,
        DISPUTE_BY_ID: (id) => `${BASE_PREFIX}/admin/thrift/disputes/${id}`,
        RESOLVE_DISPUTE: (id) => `${BASE_PREFIX}/admin/thrift/disputes/${id}/resolve`,
      },
      PAYROLL: {
        BATCH_BY_ID: (id) => `${BASE_PREFIX}/admin/payroll/batches/${id}`,
      },
      SUPPORT: {
        REPORTS: `${BASE_PREFIX}/admin/support/reports`,
        TICKETS: `${BASE_PREFIX}/admin/support/tickets`,
        TICKET_BY_ID: (id) => `${BASE_PREFIX}/admin/support/tickets/${id}`,
        ADD_MESSAGE: (id) => `${BASE_PREFIX}/admin/support/tickets/${id}/messages`,
        UPDATE_STATUS: (id) => `${BASE_PREFIX}/admin/support/tickets/${id}/status`,
      },
    },
  };
